import { createSlice } from '@reduxjs/toolkit';

import { type ReduxAction } from '@/src/redux/types';

export type Npc =
  | 'guide'
  | 'seller'
  | 'zoologist'
  | 'golfer'
  | 'bomber'
  | 'tailor'
  | 'goblin-engineer'
  | 'gunner'
  | 'paint-seller'
  | 'steampunker'
  | 'triad'
  | 'painter'
  | 'witch-doctor'
  | 'stylist'
  | 'angler'
  | 'pirate'
  | 'mechanic'
  | 'cyborg'
  | 'tax-collector'
  | 'nurse'
  | 'party-girl'
  | 'tavernkeep'
  | 'magician'
  | 'truffle';

export type Biome =
  | 'forest'
  | 'underground'
  | 'desert'
  | 'jungle'
  | 'ocean'
  | 'tundra'
  | 'holy'
  | 'glowing-mushroom-biome';

export type Rating =
  | 'very-suitable'
  | 'fits-well'
  | 'uncomfortable'
  | 'bad-fit'
  | 'absolutely not suitable'
  | 'no-data';

export type NpcState = {
  npc: Record<
    Npc,
    {
      biomes: Record<Biome, Rating>;
      neighbourhood: Record<Npc, Rating>;
    }
  >;
};

const initialState: NpcState = {
  npc: {
    guide: {
      biomes: {
        forest: 'very-suitable',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'absolutely not suitable',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    seller: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    zoologist: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    golfer: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    bomber: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    tailor: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    'goblin-engineer': {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    gunner: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    'paint-seller': {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    steampunker: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    triad: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    painter: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    'witch-doctor': {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    stylist: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    angler: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    pirate: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    mechanic: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    cyborg: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    'tax-collector': {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    nurse: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    'party-girl': {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    tavernkeep: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    magician: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
    truffle: {
      biomes: {
        forest: 'no-data',
        underground: 'no-data',
        desert: 'no-data',
        jungle: 'no-data',
        ocean: 'no-data',
        tundra: 'no-data',
        holy: 'no-data',
        'glowing-mushroom-biome': 'no-data',
      },

      neighbourhood: {
        guide: 'no-data',
        seller: 'no-data',
        zoologist: 'no-data',
        golfer: 'no-data',
        bomber: 'no-data',
        tailor: 'no-data',
        'goblin-engineer': 'no-data',
        gunner: 'no-data',
        'paint-seller': 'no-data',
        steampunker: 'no-data',
        triad: 'no-data',
        painter: 'no-data',
        'witch-doctor': 'no-data',
        stylist: 'no-data',
        angler: 'no-data',
        pirate: 'no-data',
        mechanic: 'no-data',
        cyborg: 'no-data',
        'tax-collector': 'no-data',
        nurse: 'no-data',
        'party-girl': 'no-data',
        tavernkeep: 'no-data',
        magician: 'no-data',
        truffle: 'no-data',
      },
    },
  },
};

const npcSlice = createSlice({
  name: 'npc',
  initialState,
  reducers: {
    simpleAction(state, action: ReduxAction<any>) {},
  },
});

export default npcSlice.reducer;
export const { simpleAction } = npcSlice.actions;
export const initialNpcState = npcSlice.getInitialState();
